### ISSUE TITLE
Running off master, issue in baseCommand 

### ISSUE THREAD

**Issue by Neeef** [rjt-rockx/sapphyr#14]
C:\Users\asd\OneDrive\Desktop\Sapphyr>node --no-deprecation main.js
C:\Users\asd\OneDrive\Desktop\Sapphyr\utils\baseCommand.js:17
    async run(message, arguments, fromPattern) {
                       ^^^^^^^^^

SyntaxError: Unexpected eval or arguments in strict mode
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)

**Comment by rjt-rockx** [comment]
Whoops, fixed.
